### ISSUE TITLE
Request: Tagged release(s)

### ISSUE THREAD

**Issue by HugoStrand** [hpc2n/softwareaccounting#11]
Dear all,

We would like to put this into production at C3SE, but we do not want to simply checkout the `master` branch and install. Could you please put a release tag on a commit when you are ready so that we can use that release in production?

Best regards,
Hugo

**Comment by kmjonsson** [comment]
Done.
Tag v1.0 pushed.

**Comment by HugoStrand** [comment]
Thank you!
