### ISSUE TITLE
Använd samma registrant

### ISSUE THREAD

**Issue by paran1** [hpc2n/softwareaccounting#15]
Det är mycket små skillnader på ``extras/sgas-sa-registrant/bin/sgas-sa-registrant`` i detta repo och ``bart-registrant`` (https://github.com/hpc2n/bart/blob/master/bart-registrant).

Jag föreslår att koden slås ihop och bara underhålls på ett ställe. Eventuella nödvändiga skillnader borde kunna hanteras via konfiguration/parametrar.

**Comment by kmjonsson** [comment]
Det stora problemet är att bart-registrant och sgas-sa-registrant inte underhålls av samma personer eller ens i samma projekt/organisation. Vi har några små förändringar i hpc2n-repot för bart för att enklare fungera med software accountingen men i övrigt är det sgas upstream. Att lägga större justeringar på den känns inte vettigt då den gärna får vara så nära upstream som möjligt.

Jag har pratat med sgas-maintainern om att ev skriva om bart-registrant för att ta bort twisted-beroendet och man skulle eventuellt kunna fundera på om man kunde göra några förenklingar så att samma registrant går att använda även till storage och software accounting.

**Comment by paran1** [comment]
Som "slutanvändare" tycker jag mest bara det är osnyggt att det installeras flera versioner av nästan samma kod.

sgas-sa-registrant har jag inte sett någon annan uppströms till, och ovasett så är den ju patchad hos oss. Att underhålla patchar på ett ställe borde vara enklare än på två?

Om ändringar sedan kan pushas tillbaks till t.ex. sgas/bart så är det ju bra. (hp2cn/bart har ingen issue-tracker, annars hade jag lagt det här där istället. sgas/bart har, med issues från 2013 och senare, vilket säger en del om aktiviteten där)

**Comment by kmjonsson** [comment]
Kan hålla med dig till viss del.

Jag skulle nog helst vilja skriva om registranten från början för att strippa bort beroendet av twisted. Det finns dock en hel del saker i bart (relaterat till grid. Om de behövs idag har jag lite dålig koll på) som inte behövs i software accounting-fallet och därmed skulle en omskrivning där vara mycket enklare.

Skulle vilja få med möjligheten till att göra bättre valideringar av datan innan man försöker skicka upp den också med tex XML-schema.

Som det ser ut just nu finns det tre varianter av registranten ute i det vilda. bart, storage och software accounting. Skulle tro att storage och software accounting skulle kunna slås ihop enklare än bart och de övriga (på grund av de grid-relaterade sakerna jag nämde ovan). bart-registranten gör också en del ihopslagningsmagi för att slippa skicka varje usage-record var för sig vilket i sin tur ökar komplexiteten i hanteringen. Om man föreslår att bart skriver en körning i en fil istället en fil/jobb skulle man kunna skippa den koden. Dock med lite ökat problem om det är nån del av xml:en är trasig av någon anledning.

Orsaken till att det blev en "fork" av registranten var en ren tidsbesparing för att slippa skriva en helt ny från början. 

Jag lägger detta i listan att tittas på. Det är bra med kommentarer, det gör saker bättre.

**Comment by kmjonsson** [comment]
Den nya registranten går att använda till allt.
