### ISSUE TITLE
Incorrect unused PyYAML imports

### ISSUE THREAD

**Issue by paran1** [hpc2n/softwareaccounting#17]
These PyYAML imports don't look right:

https://github.com/hpc2n/softwareaccounting/blob/5db63527e342d8988fde2db3d43c96e59f565f09/sams/base.py#L6-L9
https://github.com/hpc2n/softwareaccounting/blob/5db63527e342d8988fde2db3d43c96e59f565f09/sams/core.py#L3-L6

This comes from the fix for #1. If importing `CLoader`/`CDumper` fails we use `SafeLoader`/`SafeDumper`, which does not do the same thing.

The non-C versions of `CLoader`/`CDumper` is `Loader`/`Dumper`, and the C-versions of `SafeLoader`/`SafeDumper` is `CSafeLoader`/`CSafeDumper`.

As far as I can tell these imports are not used anywhere so a good fix is probably to remove them.

**Comment by kmjonsson** [comment]
YamlLoader is used in core.

Cleanup/fix commited but not pushed yet.

**Comment by paran1** [comment]
Oh, I see. But there is also a `import yaml` so why not:

```
diff --git a/sams/core.py b/sams/core.py
index 68356bf..1a0a4bd 100644
--- a/sams/core.py
+++ b/sams/core.py
@@ -22,3 +22,3 @@ class Config:
         with open(config_file,"r") as file:
-            self._cfg = yaml.load(file, Loader=YamlLoader)
+            self._cfg = yaml.load(file, Loader=yaml.SafeLoader)
```

**Comment by kmjonsson** [comment]
Even better.
