### ISSUE TITLE
Fel free och size-värden från ZFSStats

### ISSUE THREAD

**Issue by Micket** [hpc2n/softwareaccounting#19]
https://github.com/hpc2n/softwareaccounting/blob/a80d15222227640cb12a4589e52a636dca9e7253/sams/sampler/ZFSStats.py#L51

stämmer ej; "avail" är "free"

```
 ret[v] = dict(size=avail+used, free=avail, used=used)
```

**Comment by kmjonsson** [comment]
Fixat
