### ISSUE TITLE
Empty sams.output.File key crashes collector

### ISSUE THREAD

**Issue by paran1** [hpc2n/softwareaccounting#23]
While commenting stuff out to get a minimal config I discovered that having an empty ``sams.output.File:`` key in the config file causes the collector to crash.

I am guessing other scripts and modules might behave in a similar way, but have not verified this with anything else than the collector and ``sams.output.File:``.

```
$ cat /etc/sams/sams-collector.yaml
---
sams.collector:  
  pid_finder: sams.pidfinder.Slurm
  samplers:
    - sams.sampler.Core
    - sams.sampler.Software
  outputs:
    - sams.output.File

sams.output.File:
```

```
$ sams-collector --jobid=1 
2021-05-07 18:40:04,522 __main__:ERROR Failed to initialize: sams.output.File
2021-05-07 18:40:04,522 __main__:ERROR argument of type 'NoneType' is not iterable
```

**Comment by kmjonsson** [comment]
Fixed in v1.5
